### ISSUE TITLE
Facebook social login is not ready for non-developer users

### ISSUE THREAD

**Issue by goodtune** [internationaltouch/fit_tournaments#1]
I asked someone to test the current state of the application for me, and they were OK to log in with LinkedIn, but the Facebook connection was unable to complete.

Traceback is below.

```
[fit-tournaments] [2023-01-22 09:33:43] 2023-01-22 09:33:43,744 ERROR Internal Server Error: /complete/facebook/
[fit-tournaments] [2023-01-22 09:33:43] Traceback (most recent call last):
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
[fit-tournaments] [2023-01-22 09:33:43]     response = get_response(request)
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
[fit-tournaments] [2023-01-22 09:33:43]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
[fit-tournaments] [2023-01-22 09:33:43]     response = view_func(request, *args, **kwargs)
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[fit-tournaments] [2023-01-22 09:33:43]     return view_func(*args, **kwargs)
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/social_django/utils.py", line 46, in wrapper
[fit-tournaments] [2023-01-22 09:33:43]     return func(request, backend, *args, **kwargs)
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/social_django/views.py", line 31, in complete
[fit-tournaments] [2023-01-22 09:33:43]     return do_complete(request.backend, _do_login, user=request.user,
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/social_core/actions.py", line 45, in do_complete
[fit-tournaments] [2023-01-22 09:33:43]     user = backend.complete(user=user, *args, **kwargs)
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/social_core/backends/base.py", line 40, in complete
[fit-tournaments] [2023-01-22 09:33:43]     return self.auth_complete(*args, **kwargs)
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/social_core/utils.py", line 247, in wrapper
[fit-tournaments] [2023-01-22 09:33:43]     return func(*args, **kwargs)
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/social_core/backends/facebook.py", line 91, in auth_complete
[fit-tournaments] [2023-01-22 09:33:43]     self.process_error(self.data)
[fit-tournaments] [2023-01-22 09:33:43]   File "/workspace/.heroku/python/lib/python3.10/site-packages/social_core/backends/facebook.py", line 85, in process_error
[fit-tournaments] [2023-01-22 09:33:43]     raise AuthCanceled(self, data.get('error_message') or
[fit-tournaments] [2023-01-22 09:33:43] social_core.exceptions.AuthCanceled: Authentication process canceled: App not active: This app is not accessible right now and the app developer is aware of the issue. You will be able to log in when the app is reactivated.
```

It looks like I still need to complete the application setup on the Facebook Developer portal; I need to follow up on this.

**Comment by goodtune** [comment]
I have ticked the **Live** button on the Facebook admin pages and will test the success over the coming days - hopefully, we're ready to close this.
